apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mols
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0029-tenant/tkrw-pr712-0075-0029-app/devfile-sample-mols@sha256:99b2853506bc30a417feb00caa3d92ba3604b44c175f4d86442f64d260fa5cf9
        name: my-nodejs
        resources: {}
status: {}
